### ISSUE TITLE
Config for java-nvim

### ISSUE THREAD

**Issue by GustavoJCL** [JavaHello/spring-boot.nvim#1]
Hi, in the documentation only provides a configuration for integrate with nvim-jdtls, how can it be used with [java-nvim](https://github.com/nvim-java/nvim-java)

**Comment by JavaHello** [comment]
I have never used `java-nvim`. I looked at the code of `java-nvim` and it seems that the code needs to be modified to support it.
https://github.com/nvim-java/nvim-java-core/blob/main/lua/java-core/ls/servers/jdtls/plugins.lua#L8

**Comment by JavaHello** [comment]
> Hi, in the documentation only provides a configuration for integrate with nvim-jdtls, how can it be used with [java-nvim](https://github.com/nvim-java/nvim-java)

```lua
require("lspconfig").jdtls.setup {
  init_options = {
    bundles = require("spring_boot").java_extensions(),
  },
}

```
Try configuring like this

**Comment by JavaHello** [comment]
done  https://github.com/JavaHello/spring-boot.nvim/commit/8d258ebfdcbc1748e40bc94841edc219d87ebe87

**Comment by s1n7ax** [comment]
Right now, all you have to do is to update `nvim-java` and spring-boot is installed and setup automatically.
