### ISSUE TITLE
`spring-boot` client cannot be found on startup

### ISSUE THREAD

**Issue by chenxin-yan** [JavaHello/spring-boot.nvim#13]
<img width="816" alt="image" src="https://github.com/user-attachments/assets/9760bef7-fe67-4719-abe6-61f81029ad20" />
<img width="605" alt="image" src="https://github.com/user-attachments/assets/260c2e90-50e1-4d49-8d78-755eff1b54eb" />
<img width="375" alt="image" src="https://github.com/user-attachments/assets/ea4421b0-c31c-4504-9d53-e10e78d68a28" />

I tried configuring spring-boot.nvim with the default config provided in README.md, and the Spring-boot client cannot be found. I also tried to pass the path explicitly into the setup function, but it still doesn't work.

Spring-boot: v1.59.0
neovim: v0.10.3

**Comment by JavaHello** [comment]
Please share the output of `LspInfo`.

**Comment by chenxin-yan** [comment]
```
LSP configs active in this buffer (bufnr: 9) ~
- Language client log: ~/.local/state/nvim/lsp.log
- Detected filetype: `java`
- 2 client(s) attached to this buffer
- Client: `jdtls` (id: 1, bufnr: [9])
  root directory:    ~/dev/demo/
  filetypes:         
  cmd:               ~/dev/demo/src/main/java/com/example/demo/java -Declipse.application=org.eclipse.jdt.ls.core.id1 -Dosgi.bundles.defaultStartLevel=4 -Declipse.product=org.eclipse.jdt.ls.core.product -Dlog.protocol=true -Dlog.level=ALL -javaagent:/Users/yanchenxin/.local/share/nvim/mason/share/jdtls/lombok.jar -Xmx4g --add-modules=ALL-SYSTEM --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED -jar /Users/yanchenxin/.local/share/nvim/mason/share/jdtls/plugins/org.eclipse.equinox.launcher.jar -configuration /Users/yanchenxin/.local/share/nvim/mason/packages/jdtls/config_mac_arm -data /Users/yanchenxin/jdtls-workspace/demo
  version:           `java 17.0.12 2024-07-16 LTS`
  executable:        true
  autostart:         false
- Client: `copilot` (id: 2, bufnr: [9])
  root directory:    ~/dev/demo/src/main/java/com/example/demo/
  filetypes:         
  cmd:               ~/dev/demo/src/main/java/com/example/demo/node /Users/yanchenxin/.local/share/nvim/lazy/copilot.lua/copilot/index.js
  version:           `v22.11.0`
  executable:        true
  autostart:         false

Docs for active configs: ~
- 
- 
```

**Comment by chenxin-yan** [comment]
Here is my [java ft](https://github.com/chenxin-yan/nvim/blob/a9a7694393c18c286f9f76c5b5e8263a72d38923/after/ftplugin/java.lua#L12) and [lspconfig](https://github.com/chenxin-yan/nvim/blob/a9a7694393c18c286f9f76c5b5e8263a72d38923/lua/cyan/plugins/lspconfig.lua#L310-L337)

**Comment by JavaHello** [comment]
It might be because `ftplugin` is loaded before the `filetype` event, so `jdtls` has already started, but `spring-boot` has not yet started.
I have added the waiting logic in the latest commit. Please try again.
https://github.com/JavaHello/spring-boot.nvim/commit/21483b5cf3dd4bfa16f498f7a28d11e7b34aa2ec

**Comment by chenxin-yan** [comment]
I received a message after opening a Java file: `Spring Boot LS is not ready, waiting for start` after `jdtls` started, and Spring Boot LS is still not loaded. Do you have a recommended setup for working with `jdtls`? Thanks.

**Comment by JavaHello** [comment]
Here is my configuration.
[plugins](https://github.com/JavaHello/nvim/blob/nvchad/lua/plugins/init.lua#L190)
[lspconfig](https://github.com/JavaHello/nvim/blob/nvchad/lua/configs/lspconfig.lua#L76)
Try to start a simple `Maven` project.
```txt
├── .git
├── mvnw
├── pom.xml
└── src
```

**Comment by chenxin-yan** [comment]
The issue is fixed and was caused by lazy loading. To lazy load `spring-boot`, set the event to `BufReadPre`. This will ensure it starts before `jdtls` in `ftplugin`. Here is my [config](https://github.com/chenxin-yan/nvim/blob/main/lua/cyan/plugins/spring-boot.lua).

**Comment by JavaHello** [comment]
Thank you. Could you try adding `model = "spring_boot",` to the configuration? Use the `model` method to trigger the loading of `spring-boot`. This might resolve the issue.
```lua
  {
    "JavaHello/spring-boot.nvim",
    model = "spring_boot",
    ...
  }
```

**Comment by chenxin-yan** [comment]
the problem was fixed after I change `ft = 'java'` to `event = "BufReadPre"`
