### ISSUE TITLE
如何运行spring boot 项目

### ISSUE THREAD

**Issue by imkratos** [JavaHello/spring-boot.nvim#2]
请问如何运行spring boot项目呀，我在文档中没看到，看了下代码也没太看懂。 感谢 。

**Comment by JavaHello** [comment]
需要配置 [dap](https://github.com/mfussenegger/nvim-dap) 和 [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls)，使用 `JdtRun` 运行 main 方法（这命令会先自动项目里面所有的 main 方法）
