### ISSUE TITLE
Specify java home in the setup function

### ISSUE THREAD

**Issue by sangramsingha** [JavaHello/spring-boot.nvim#4]
I have most of the project running on java 8 and since LS require java higher than 8. Is there a way to specify same in setup function

**Comment by JavaHello** [comment]
Running `jdtls` and `spring-boot-ls` requires at least jdk11 version. You can try to configure different jdk versions for running jdtls and compiling the project.

**Comment by sangramsingha** [comment]
Thanks for the info
