### ISSUE TITLE
Is VS Code compulsory?

### ISSUE THREAD

**Issue by nithin-mk** [JavaHello/spring-boot.nvim#5]
Is it compulsory to install [VScode Spring Boot](https://marketplace.visualstudio.com/items?itemName=vmware.vscode-spring-boot) extension in [Visual Studio Code](https://code.visualstudio.com/) accoording to the README? If I don't have VS Code, would spring-boot.nvim be able to download the required Spring Tools 4 files and work by itself?

**Comment by JavaHello** [comment]
It will not be downloaded automatically. If you do not use vscode, you need to manually download the compiled jar.

**Comment by nithin-mk** [comment]
Thank you for your reply. From which website can I download the JAR from - VSCode Marketplace or Spring Tools website?

**Comment by JavaHello** [comment]
You can directly download the vscode [spring-boot-tools](https://marketplace.visualstudio.com/items?itemName=vmware.vscode-spring-boot) plugin and unzip it, or download the sts4 project and compile it.

**Comment by jonathan-elize** [comment]
I got around this by using what [nvim-java](https://github.com/nvim-java/nvim-java) does. The author of `nvim-java` made a [mason](https://github.com/williamboman/mason.nvim) regsitry that would get you the jars needed.

In all this is what I did:

1. I updated my `mason.setup` call to also use the `nvim-java` repository as a source:
```lua
            require("mason").setup({
              registries = {
                "github:mason-org/mason-registry",
                "github:nvim-java/mason-registry",
              },
            })
```
2. I installed `spring-boot-tools` through `:Mason`
3. I added the bundle of jars to my [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) setup accordingly:
```lua
    local spring_path = require("mason-registry")
      .get_package("spring-boot-tools")
      :get_install_path() .. "/extension/jars/*.jar"
    local spring = vim.split(vim.fn.glob(spring_path), "\n", {})
    vim.list_extend(bundles, spring)
```

**Comment by nithin-mk** [comment]
@jonathan-elize Thank you!

**Comment by oysandvik94** [comment]
@jonathan-elize Couldnt quite get this to work, are you doing this together with JavaHello/spring-boot.nvim?

**Comment by logrusx** [comment]
> I got around this by using what [nvim-java](https://github.com/nvim-java/nvim-java) does. The author of `nvim-java` made a [mason](https://github.com/williamboman/mason.nvim) regsitry that would get you the jars needed.
> 
> In all this is what I did:
> 
>     1. I updated my `mason.setup` call to also use the `nvim-java` repository as a source:
> 
> 
> require("mason").setup({
>     registries = {
>         "github:mason-org/mason-registry",
>         "github:nvim-java/mason-registry",
>     },
> })

That is not necessary anymore
> 
>     2. I installed `spring-boot-tools` through `:Mason`
> 

Mason repository now includes vscode-spring-boot-tools
>     3. I added the bundle of jars to my [nvim-jdtls](https://github.com/mfussenegger/nvim-jdtls) setup accordingly:
> 
> 
> local spring_path = require("mason-registry")
>     .get_package("spring-boot-tools")

So the above should be changed to `.get_package("vscode-spring-boot-tools")`

>      :get_install_path() .. "/extension/jars/*.jar"
> local spring = vim.split(vim.fn.glob(spring_path), "\n", {})
> vim.list_extend(bundles, spring)

And it should work like that. I haven't tested it though.
